# Generated by Django 3.2 on 2022-01-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('harga', models.FloatField()),
                ('diskon', models.FloatField()),
                ('kategori', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
