# Generated by Django 3.2 on 2022-01-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('alamat', models.CharField(max_length=300)),
                ('provinsi', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=300)),
                ('kecamatan', models.CharField(max_length=300)),
                ('kelurahan', models.CharField(max_length=300)),
                ('kodepos', models.CharField(max_length=300)),
            ],
        ),
    ]
