# Generated by Django 3.2 on 2022-01-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0003_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=5000000, max_length=200),
            preserve_default=False,
        ),
    ]
