# Generated by Django 3.2 on 2022-01-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0004_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
