# Generated by Django 3.2 on 2022-01-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0005_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=3000, max_length=300),
            preserve_default=False,
        ),
    ]
